#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef SYBRIN_IOS_IDENTITY_SWIFT_H
#define SYBRIN_IOS_IDENTITY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import Sybrin_iOS_Common;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Sybrin_iOS_Identity",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM(NSInteger, CitizenshipType, open) {
  CitizenshipTypeCitizen = 0,
  CitizenshipTypePermanentResident = 1,
  CitizenshipTypeUnknown = 2,
};

typedef SWIFT_ENUM(NSInteger, Country, open) {
  CountryAngola = 0,
  CountryBangladesh = 1,
  CountryBotswana = 2,
  CountryDemocraticRepublicOfTheCongo = 3,
  CountryEgypt = 4,
  CountryEthiopia = 5,
  CountryGeneric = 6,
  CountryGhana = 7,
  CountryKenya = 8,
  CountryLesotho = 9,
  CountryMalawi = 10,
  CountryMauritius = 11,
  CountryMozambique = 12,
  CountryNamibia = 13,
  CountryNigeria = 14,
  CountryPakistan = 15,
  CountryPhilippines = 16,
  CountrySomalia = 17,
  CountrySouthAfrica = 18,
  CountryTanzania = 19,
  CountryUganda = 20,
  CountryUnitedKingdom = 21,
  CountryZambia = 22,
  CountryZimbabwe = 23,
};

typedef SWIFT_ENUM(NSInteger, CutOutType, open) {
  CutOutTypeDEFAULT = 0,
  CutOutTypePASSPORT = 1,
  CutOutTypeID_CARD = 2,
  CutOutTypeACCESS_CARD = 3,
  CutOutTypeBOOK = 4,
  CutOutTypeA4 = 5,
  CutOutTypeA4_LANDSCAPE = 6,
  CutOutTypeNONE = 7,
};

typedef SWIFT_ENUM(NSInteger, Document, open) {
  DocumentGenericDocument = 0,
  DocumentPhilippinesDriversLicense = 1,
  DocumentPhilippinesFirearmsLicense = 2,
  DocumentPhilippinesIntegratedBarID = 3,
  DocumentPhilippinesPassport = 4,
  DocumentPhilippinesPhilHealthInsuranceCard = 5,
  DocumentPhilippinesPostalID = 6,
  DocumentPhilippinesProfessionalRegulationCommissionCard = 7,
  DocumentPhilippinesSeafarerIdentificationDocument = 8,
  DocumentPhilippinesSeafarerIdentificationRecordBook = 9,
  DocumentPhilippinesSocialSecurityID = 10,
  DocumentPhilippinesUnifiedMultipurposeID = 11,
  DocumentPhilippinesIdentificationCard = 12,
  DocumentPhilippinesQCIdentificationCard = 13,
  DocumentSouthAfricaGreenBook = 14,
  DocumentSouthAfricaIDCard = 15,
  DocumentSouthAfricaPassport = 16,
};

@class UIImage;
@class NSString;

SWIFT_CLASS("_TtC19Sybrin_iOS_Identity13DocumentModel")
@interface DocumentModel : NSObject
@property (nonatomic, readonly, strong) UIImage * _Nullable portraitImage;
@property (nonatomic, readonly, strong) UIImage * _Nullable documentImage;
@property (nonatomic, readonly, strong) UIImage * _Nullable croppedDocumentImage;
@property (nonatomic, readonly, copy) NSString * _Nullable portraitImagePath;
@property (nonatomic, readonly, copy) NSString * _Nullable documentImagePath;
@property (nonatomic, readonly, copy) NSString * _Nullable croppedDocumentImagePath;
- (void)saveImages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, DocumentType, open) {
  DocumentTypeDocument = 0,
  DocumentTypeDriversLicense = 1,
  DocumentTypeGreenBook = 2,
  DocumentTypeIDCard = 3,
  DocumentTypePassport = 4,
  DocumentTypeVisa = 5,
  DocumentTypeFirearmsLicense = 6,
  DocumentTypeIntegratedBarID = 7,
  DocumentTypePhilHealthInsuranceCard = 8,
  DocumentTypePostalID = 9,
  DocumentTypeProfessionalRegulationCommissionCard = 10,
  DocumentTypeSeafarerIdentificationDocument = 11,
  DocumentTypeSeafarerIdentificationRecordBook = 12,
  DocumentTypeSocialSecurityID = 13,
  DocumentTypeUnifiedMultipurposeID = 14,
  DocumentTypeQCIdentificationCard = 15,
};


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity19DriversLicenseModel")
@interface DriversLicenseModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable licenseNumber;
@property (nonatomic, readonly, strong) UIImage * _Nullable documentBackImage;
@property (nonatomic, readonly, copy) NSString * _Nullable documentBackImagePath;
- (void)saveImages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity20GenericDocumentModel")
@interface GenericDocumentModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable result;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;
enum Sex : NSInteger;

SWIFT_CLASS("_TtC19Sybrin_iOS_Identity13PassportModel")
@interface PassportModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable passportType;
@property (nonatomic, readonly, copy) NSString * _Nullable issuingCountryCode;
@property (nonatomic, readonly, copy) NSString * _Nullable surname;
@property (nonatomic, readonly, copy) NSString * _Nullable names;
@property (nonatomic, readonly, copy) NSString * _Nullable passportNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable nationality;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfBirth;
@property (nonatomic, readonly) enum Sex sex;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfExpiry;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity20GenericPassportModel")
@interface GenericPassportModel : PassportModel
@property (nonatomic, readonly, copy) NSString * _Nullable mrzLine1;
@property (nonatomic, readonly, copy) NSString * _Nullable mrzLine2;
@property (nonatomic, readonly) NSInteger passportNumberCheckDigit;
@property (nonatomic, readonly) NSInteger dateOfBirthCheckDigit;
@property (nonatomic, readonly) NSInteger dateOfExpiryCheckDigit;
@property (nonatomic, readonly, copy) NSString * _Nullable optionalData;
@property (nonatomic, readonly) NSInteger optionalDataCheckDigit;
@property (nonatomic, readonly) NSInteger compositeCheckDigit;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum GreenBookType : NSInteger;

SWIFT_CLASS("_TtC19Sybrin_iOS_Identity14GreenBookModel")
@interface GreenBookModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable identityNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable surname;
@property (nonatomic, readonly, copy) NSString * _Nullable firstNames;
@property (nonatomic, readonly, copy) NSString * _Nullable countryOfBirth;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfBirth;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateIssued;
@property (nonatomic, readonly) enum GreenBookType bookType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, GreenBookType, open) {
  GreenBookTypeBilingual = 0,
  GreenBookTypeEnglish = 1,
  GreenBookTypeUnspecified = 2,
};

typedef SWIFT_ENUM(NSInteger, HasBackSide, open) {
  HasBackSideDEFAULT = 0,
  HasBackSideTRUE = 1,
  HasBackSideFALSE = 2,
};


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity11IDCardModel")
@interface IDCardModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly) enum Sex sex;
@property (nonatomic, readonly, copy) NSString * _Nullable nationality;
@property (nonatomic, readonly, copy) NSString * _Nullable identityNumber;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfBirth;
@property (nonatomic, readonly, strong) UIImage * _Nullable portraitBackImage;
@property (nonatomic, readonly, strong) UIImage * _Nullable documentBackImage;
@property (nonatomic, readonly, strong) UIImage * _Nullable croppedDocumentBackImage;
@property (nonatomic, readonly, copy) NSString * _Nullable portraitBackImagePath;
@property (nonatomic, readonly, copy) NSString * _Nullable documentBackImagePath;
@property (nonatomic, readonly, copy) NSString * _Nullable croppedDocumentBackImagePath;
- (void)saveImages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC19Sybrin_iOS_Identity30PhilippinesDriversLicenseModel")
@interface PhilippinesDriversLicenseModel : DriversLicenseModel
@property (nonatomic, readonly, copy) NSString * _Nullable names;
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
@property (nonatomic, readonly, copy) NSString * _Nullable nationality;
@property (nonatomic, readonly) enum Sex sex;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfBirth;
@property (nonatomic, readonly, copy) NSString * _Nullable address;
@property (nonatomic, readonly, copy) NSDate * _Nullable expirationDate;
@property (nonatomic, readonly, copy) NSString * _Nullable agencyCode;
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (void)saveImages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity31PhilippinesFirearmsLicenseModel")
@interface PhilippinesFirearmsLicenseModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly, copy) NSString * _Nullable licenseToOwnAndPossessFirearmNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable qualification;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateApproved;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateExpiry;
@property (nonatomic, readonly, copy) NSString * _Nullable otherLicenses;
@property (nonatomic, readonly, copy) NSString * _Nullable address;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity34PhilippinesIdentificationCardModel")
@interface PhilippinesIdentificationCardModel : IDCardModel
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly, copy) NSString * _Nullable address;
@property (nonatomic, readonly, copy) NSString * _Nullable bloodType;
@property (nonatomic, readonly, copy) NSString * _Nullable commonReferenceNumber;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfIssued;
@property (nonatomic, readonly, copy) NSString * _Nullable givenNames;
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
@property (nonatomic, readonly, copy) NSString * _Nullable maritalStatus;
@property (nonatomic, readonly, copy) NSString * _Nullable middleName;
@property (nonatomic, readonly, copy) NSString * _Nullable placeOfBirth;
@property (nonatomic, readonly) enum Sex idSex;
@property (nonatomic, readonly, copy) NSDate * _Nullable idDateOfBirth;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (void)saveImages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity31PhilippinesIntegratedBarIDModel")
@interface PhilippinesIntegratedBarIDModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly, copy) NSString * _Nullable rollOfAttorneysNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable integratedBarPhilippinesChapter;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity24PhilippinesPassportModel")
@interface PhilippinesPassportModel : PassportModel
@property (nonatomic, readonly, copy) NSString * _Nullable mrzLine1;
@property (nonatomic, readonly, copy) NSString * _Nullable mrzLine2;
@property (nonatomic, readonly) NSInteger passportNumberCheckDigit;
@property (nonatomic, readonly) NSInteger dateOfBirthCheckDigit;
@property (nonatomic, readonly) NSInteger dateOfExpiryCheckDigit;
@property (nonatomic, readonly) NSInteger compositeCheckDigit;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity39PhilippinesPhilHealthInsuranceCardModel")
@interface PhilippinesPhilHealthInsuranceCardModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable philHealthNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfBirth;
@property (nonatomic, readonly) enum Sex sex;
@property (nonatomic, readonly, copy) NSString * _Nullable address;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity24PhilippinesPostalIDModel")
@interface PhilippinesPostalIDModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly, copy) NSString * _Nullable postalReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable address;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfBirth;
@property (nonatomic, readonly, copy) NSDate * _Nullable validUntil;
@property (nonatomic, readonly, copy) NSString * _Nullable nationality;
@property (nonatomic, readonly, copy) NSString * _Nullable issuingPostOffice;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardType;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity52PhilippinesProfessionalRegulationCommissionCardModel")
@interface PhilippinesProfessionalRegulationCommissionCardModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
@property (nonatomic, readonly, copy) NSString * _Nullable middleInitialName;
@property (nonatomic, readonly, copy) NSString * _Nullable registrationNumber;
@property (nonatomic, readonly, copy) NSDate * _Nullable registrationDate;
@property (nonatomic, readonly, copy) NSDate * _Nullable validUntil;
@property (nonatomic, readonly, copy) NSString * _Nullable profession;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfBirth;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateIssued;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity36PhilippinesQCIdentificationCardModel")
@interface PhilippinesQCIdentificationCardModel : IDCardModel
@property (nonatomic, readonly, copy) NSString * _Nullable civilStatus;
@property (nonatomic, readonly, copy) NSString * _Nullable bloodType;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateIssued;
@property (nonatomic, readonly, copy) NSDate * _Nullable validUntil;
@property (nonatomic, readonly, copy) NSString * _Nullable disabilityType;
@property (nonatomic, readonly, copy) NSString * _Nullable citizenType;
@property (nonatomic, readonly, copy) NSString * _Nullable address;
@property (nonatomic, readonly, copy) NSString * _Nullable qcReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable barcodeData;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity46PhilippinesSeafarerIdentificationDocumentModel")
@interface PhilippinesSeafarerIdentificationDocumentModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable mrzLine1;
@property (nonatomic, readonly, copy) NSString * _Nullable mrzLine2;
@property (nonatomic, readonly, copy) NSString * _Nullable mrzLine3;
@property (nonatomic, readonly, copy) NSString * _Nullable documentType;
@property (nonatomic, readonly, copy) NSString * _Nullable issuingCountryCode;
@property (nonatomic, readonly, copy) NSString * _Nullable identityNumber;
@property (nonatomic, readonly) NSInteger identityNumberCheckDigit;
@property (nonatomic, readonly, copy) NSString * _Nullable optionalData1;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfBirth;
@property (nonatomic, readonly) NSInteger dateOfBirthCheckDigit;
@property (nonatomic, readonly) enum Sex sex;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfExpiry;
@property (nonatomic, readonly) NSInteger dateOfExpiryCheckDigit;
@property (nonatomic, readonly, copy) NSString * _Nullable nationality;
@property (nonatomic, readonly, copy) NSString * _Nullable optionalData2;
@property (nonatomic, readonly) NSInteger compositeCheckDigit;
@property (nonatomic, readonly, copy) NSString * _Nullable surname;
@property (nonatomic, readonly, copy) NSString * _Nullable names;
@property (nonatomic, readonly, strong) UIImage * _Nullable portraitBackImage;
@property (nonatomic, readonly, strong) UIImage * _Nullable documentBackImage;
@property (nonatomic, readonly, strong) UIImage * _Nullable croppedDocumentBackImage;
@property (nonatomic, readonly, copy) NSString * _Nullable portraitBackImagePath;
@property (nonatomic, readonly, copy) NSString * _Nullable documentBackImagePath;
@property (nonatomic, readonly, copy) NSString * _Nullable croppedDocumentBackImagePath;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (void)saveImages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity48PhilippinesSeafarerIdentificationRecordBookModel")
@interface PhilippinesSeafarerIdentificationRecordBookModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfBirth;
@property (nonatomic, readonly, copy) NSString * _Nullable placeOfBirth;
@property (nonatomic, readonly) float height;
@property (nonatomic, readonly) float weight;
@property (nonatomic, readonly, copy) NSString * _Nullable eyeColor;
@property (nonatomic, readonly, copy) NSString * _Nullable hairColor;
@property (nonatomic, readonly, copy) NSString * _Nullable distinguishingMarks;
@property (nonatomic, readonly) enum Sex sex;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfIssue;
@property (nonatomic, readonly, copy) NSString * _Nullable placeOfIssue;
@property (nonatomic, readonly, copy) NSDate * _Nullable validUntil;
@property (nonatomic, readonly, copy) NSString * _Nullable documentNumber;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity32PhilippinesSocialSecurityIDModel")
@interface PhilippinesSocialSecurityIDModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable socialSecurityNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfBirth;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity37PhilippinesUnifiedMultipurposeIDModel")
@interface PhilippinesUnifiedMultipurposeIDModel : DocumentModel
@property (nonatomic, readonly, copy) NSString * _Nullable commonReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable surname;
@property (nonatomic, readonly, copy) NSString * _Nullable givenName;
@property (nonatomic, readonly, copy) NSString * _Nullable middleName;
@property (nonatomic, readonly) enum Sex sex;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfBirth;
@property (nonatomic, readonly, copy) NSString * _Nullable address;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, Sex, open) {
  SexMale = 0,
  SexFemale = 1,
  SexUndetermined = 2,
};


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity25SouthAfricaGreenBookModel")
@interface SouthAfricaGreenBookModel : GreenBookModel
@property (nonatomic, readonly, copy) NSDate * _Nullable identityNumberDateOfBirth;
@property (nonatomic, readonly) enum Sex identityNumberSex;
@property (nonatomic, readonly) enum CitizenshipType identityNumberCitizenship;
@property (nonatomic, readonly) NSInteger identityNumberADigit;
@property (nonatomic, readonly) NSInteger identityNumberCheckDigit;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity22SouthAfricaIDCardModel")
@interface SouthAfricaIDCardModel : IDCardModel
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly, copy) NSString * _Nullable surname;
@property (nonatomic, readonly, copy) NSString * _Nullable names;
@property (nonatomic, readonly, copy) NSDate * _Nullable identityNumberDateOfBirth;
@property (nonatomic, readonly) enum Sex identityNumberSex;
@property (nonatomic, readonly) enum CitizenshipType identityNumberCitizenship;
@property (nonatomic, readonly) NSInteger identityNumberADigit;
@property (nonatomic, readonly) NSInteger identityNumberCheckDigit;
@property (nonatomic, readonly, copy) NSString * _Nullable countryOfBirth;
@property (nonatomic, readonly) enum CitizenshipType citizenship;
@property (nonatomic, readonly, copy) NSDate * _Nullable dateIssued;
@property (nonatomic, readonly, copy) NSString * _Nullable rsaCode;
@property (nonatomic, readonly, copy) NSString * _Nullable cardNumber;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19Sybrin_iOS_Identity24SouthAfricaPassportModel")
@interface SouthAfricaPassportModel : PassportModel
@property (nonatomic, readonly, copy) NSString * _Nullable mrzLine1;
@property (nonatomic, readonly, copy) NSString * _Nullable mrzLine2;
@property (nonatomic, readonly) NSInteger passportNumberCheckDigit;
@property (nonatomic, readonly) NSInteger dateOfBirthCheckDigit;
@property (nonatomic, readonly) NSInteger dateOfExpiryCheckDigit;
@property (nonatomic, readonly, copy) NSString * _Nullable identityNumber;
@property (nonatomic, readonly, copy) NSDate * _Nullable identityNumberDateOfBirth;
@property (nonatomic, readonly) enum Sex identityNumberSex;
@property (nonatomic, readonly) enum CitizenshipType identityNumberCitizenship;
@property (nonatomic, readonly) NSInteger identityNumberADigit;
@property (nonatomic, readonly) NSInteger identityNumberCheckDigit;
@property (nonatomic, readonly) NSInteger identityNumberPassportCheckDigit;
@property (nonatomic, readonly) NSInteger compositeCheckDigit;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable wordConfidenceResults;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SybrinIdentityConfiguration;
@class UIViewController;

SWIFT_CLASS("_TtC19Sybrin_iOS_Identity14SybrinIdentity")
@interface SybrinIdentity : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SybrinIdentity * _Nonnull shared;)
+ (SybrinIdentity * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) SybrinIdentityConfiguration * _Nullable configuration;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)changeLogLevelTo:(enum LogLevel)logLevel;
- (void)scanDocumentOn:(UIViewController * _Nonnull)viewController for:(enum Document)document cutOutType:(enum CutOutType)cutOutType hasBackSide:(enum HasBackSide)hasBackSide doneLaunching:(void (^ _Nullable)(BOOL, NSString * _Nullable))doneLaunching success:(void (^ _Nullable)(DocumentModel * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure cancel:(void (^ _Nullable)(void))cancel;
- (void)scanDriversLicenseOn:(UIViewController * _Nonnull)viewController for:(enum Country)country cutOutType:(enum CutOutType)cutOutType hasBackSide:(enum HasBackSide)hasBackSide doneLaunching:(void (^ _Nullable)(BOOL, NSString * _Nullable))doneLaunching success:(void (^ _Nullable)(DriversLicenseModel * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure cancel:(void (^ _Nullable)(void))cancel;
- (void)scanGreenBookOn:(UIViewController * _Nonnull)viewController doneLaunching:(void (^ _Nullable)(BOOL, NSString * _Nullable))doneLaunching success:(void (^ _Nullable)(GreenBookModel * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure cancel:(void (^ _Nullable)(void))cancel;
- (void)scanIDCardOn:(UIViewController * _Nonnull)viewController for:(enum Country)country doneLaunching:(void (^ _Nullable)(BOOL, NSString * _Nullable))doneLaunching success:(void (^ _Nullable)(IDCardModel * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure cancel:(void (^ _Nullable)(void))cancel;
- (void)scanPassportOn:(UIViewController * _Nonnull)viewController for:(enum Country)country doneLaunching:(void (^ _Nullable)(BOOL, NSString * _Nullable))doneLaunching success:(void (^ _Nullable)(PassportModel * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure cancel:(void (^ _Nullable)(void))cancel;
@end


@class UIColor;

SWIFT_CLASS("_TtC19Sybrin_iOS_Identity27SybrinIdentityConfiguration")
@interface SybrinIdentityConfiguration : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull license;
@property (nonatomic, strong) UIColor * _Nonnull overlayColor;
@property (nonatomic, strong) UIColor * _Nonnull overlayLabelTextColor;
@property (nonatomic, strong) UIColor * _Nonnull overlaySubLabelTextColor;
@property (nonatomic, strong) UIColor * _Nonnull overlayBorderColor;
@property (nonatomic) CGFloat overlayBorderThickness;
@property (nonatomic) CGFloat overlayBorderLength;
@property (nonatomic) enum UIBlurEffectStyle overlayBlurStyle;
@property (nonatomic) CGFloat overlayBlurIntensity;
@property (nonatomic) enum AVCaptureDevicePosition cameraPosition;
@property (nonatomic, copy) NSString * _Nonnull environmentKey;
@property (nonatomic, copy) NSString * _Nonnull overlayBrandingTitleText;
@property (nonatomic, strong) UIColor * _Nonnull overlayBrandingTitleColor;
@property (nonatomic, copy) NSString * _Nonnull overlayBrandingSubtitleText;
@property (nonatomic, strong) UIColor * _Nonnull overlayBrandingSubtitleColor;
@property (nonatomic) BOOL enableBackButton;
@property (nonatomic) BOOL enableSwipeRightGesture;
@property (nonatomic) BOOL showFlashButton;
@property (nonatomic) BOOL displayToastMessages;
@property (nonatomic) BOOL saveImages;
@property (nonatomic) CGFloat cutoutCornerRadius;
@property (nonatomic) BOOL enableMultiPhaseVerification;
@property (nonatomic) BOOL enableHelpMessages;
@property (nonatomic, copy) NSString * _Nullable correlationID;
@property (nonatomic, copy) NSString * _Nullable customAuthorizationToken;
- (nonnull instancetype)initWithLicense:(NSString * _Nonnull)license OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end






#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
